name: Docker CI/CD when PR to Main.

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get branch name (pull request)
        if: github.event_name == 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV

      - name: Check out code
        uses: actions/checkout@v3

      - name: Build Docker images
        run: |
          docker build . -t digivisio2030.azurecr.io/react18:${{ env.BRANCH_NAME }}
